### ISSUE TITLE
Índice entre datas não funciona

### ISSUE THREAD

**Issue by victortrindade1** [thefintz/docs#6]
Cara, parabéns pela API! Fazendo de acordo com a documentacao, o índice entre datas está fora do ar. 

Request GET: {{ _.base_url }}/indexes/cdi/profitability?start=2022-08-01&end=2022-08-05

Response: status 500 Internal Server Error

base_url = https://0o1jvhh5z7.execute-api.us-east-2.amazonaws.com

**Comment by meyer1994** [comment]
Muito obrigado pelo feedback @victortrindade1

Já identificamos o problema e estamos trabalhando no fix. Estará arrumado em breve. Enquanto isso, recomendamos dar uma olhada na nossa API V2 no link abaixo.

https://api.fintz.com.br/docs

Ficamos no aguardo de novos issues 😄

**Comment by victortrindade1** [comment]
Não tendo nada a ver com a issue, vcs tem plano de colocar mais benchmarks na api dos Índices? 
Ex: IBrX, IPCA, SMLL, IFIX... 
Eu to perguntando pq meu intuito é automatizar o sharpe de todos os fundos

**Comment by mauriciomb97** [comment]
Fala Victor, o fix já está em produção. Pode conferir aqui:
https://0o1jvhh5z7.execute-api.us-east-2.amazonaws.com/indexes/cdi/profitability?start=2022-08-01&end=2022-08-05

Sim, temos planos de aumentar a quantidade de benchmarks disponíveis, adicionei os que você mencionou no nosso backlog, Fique a vontade para sugerir outros também.

**Comment by gmbueno** [comment]
@victortrindade1 acabamos não te avisando, mas agora todos esses índices estão na API
